name: WINDOWS 2022 RDP
on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999
    steps:
      - name: Download Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/start.bat -OutFile start.bat
          Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/download1.jpeg -OutFile wallpaper.bat
          Invoke-WebRequest https://raw.githubusercontent.com/Vip3rLi0n/Ngrok-RDPs/main/resources/loop.ps1 -OutFile loop.ps1
          
      - name: Extract Ngrok
        run: Expand-Archive ngrok.zip
        
      - name: Connect Ngrok
        run: |
          ./ngrok/ngrok.exe authtoken 341Cgd8QHfEBLmz9FrVzEDt1e8Q_5f8d9DJMDJzgQGJ3M2oW5
          Write-Host "Ngrok token configured successfully!"
          
      - name: Enable Windows RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' -name "UserAuthentication" -Value 1
          copy wallpaper.bat D:\\a\\wallpaper.bat
          Write-Host "RDP Enabled!"
          
      - name: Start Ngrok Tunnel
        run: |
          Start-Process PowerShell -ArgumentList '-NoExit -Command "./ngrok/ngrok.exe tcp --region ap 3389"'
          Start-Sleep -Seconds 10
          Write-Host "Tunnel started!"
          
      - name: Get Ngrok URL
        run: |
          Start-Sleep -Seconds 5
          $response = Invoke-RestMethod -Uri http://localhost:4040/api/tunnels
          $publicUrl = $response.tunnels[0].public_url
          Write-Host "=========================================="
          Write-Host "RDP CONNECTION URL: $publicUrl"
          Write-Host "=========================================="
          
      - name: Connect RDP
        run: cmd /c start.bat
        
      - name: Keep Alive
        run: |
          Write-Host "Session is running..."
          while ($true) {
            Start-Sleep -Seconds 60
            Write-Host "Active - $(Get-Date -Format 'HH:mm:ss')"
          }
